# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodMenu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodMenu
	pod 'Alamofire', '5.4.2'
 	pod 'RxSwift', '5.1'
  pod 'RxCocoa', '5.1'
  pod 'SDWebImage', '5.10.0'
  pod 'RxSwiftUtilities', '~> 2.2.0'
  pod 'MBProgressHUD', '1.2.0'
  pod 'Reusable', '4.1.1'	
	pod 'Then', '~> 3.0.0'


end
